// ============================================================
// THE FREQUENCY — PRODIGAL ROBE
// MASTER CHANNEL CONFIG v1.0
// ============================================================
// To add a channel: copy a block, fill in the fields, done.
// Categories: favorites | church | real-talk | pulpit |
//             apologetics | street | prophecy | creation |
//             history | music | comedy | catholic | ambient
// ============================================================

const FQ_CHANNELS = [

  // ── FAVORITES ────────────────────────────────────────────

  {
    number: '01',
    name: 'Unchained Podcast',
    host: 'Alex & Richie',
    type: 'PODCAST',
    category: 'favorites',
    vibe: 'raw',
    desc: 'Breaking chains. Building freedom in Christ. The flagship Prodigal Robe channel.',
    website: 'https://losingfaithbook.com',
    youtubeChannelId: 'UCU6C2VnIne4gDz1U_Y1ifMw',
    thumbUrl: '',
    isLive: false,
    videoIds: [
      'KRbz28FnRd8','lUAd0KmMqVM','IFNLlEZYJTk',
      '_E2Dg5HP2hY','CbTFT2CVKlA','kp2a4x0zifM',
      'YZM5kJ4NXaI','MKTPhe5Xdck','lPBrrgCZNLo',
      '5I7U8jLJ8co','uCz8NQn_qEE'
    ],
  },

  {
    number: '02',
    name: 'Authentic Church',
    host: 'Pastor Bobby Chandler',
    type: 'CHURCH',
    category: 'favorites',
    vibe: 'intense',
    desc: 'Encounter God. Be set free. Hickory, NC.',
    website: 'https://authenticchurch.com',
    youtubeChannelId: 'UCw0A4_ow3IhwaQklrTiK_Cg',
    thumbUrl: 'https://yt3.googleusercontent.com/ytc/AIdro_l1rPaHxqxa5UtjqiP-c1pkdlpH5V3KFvXzqiFWInJnqG0=s176-c-k-c0x00ffffff-no-rj',
    isLive: true,
    videoIds: [
      '0G1C_-ALojI','stPDLL0mIps','0hj-1lCC4hE',
      '2tlxp3Bj3B8','94YbN89m9-I','bZsDpCvr5Vs',
      'B4EHT5J93oU','-i1CXARmcN8','df_-Ss5LOo4',
      'KpagsrOWwvU'
    ],
  },

  {
    number: '03',
    name: '2819 Church',
    host: 'Philip Anthony Mitchell',
    type: 'CHURCH',
    category: 'favorites',
    vibe: 'deep',
    desc: 'Confronting culture with biblical truth. Atlanta, GA.',
    website: 'https://2819church.org',
    youtubeChannelId: 'UCrPGIKiPtgQ25TaW1fLdR0Q',
    thumbUrl: 'https://yt3.googleusercontent.com/ytc/AIdro_kpbvQWrYBhB6LwJUgGHDUgN8A8zMRqw_2BRm4=s176-c-k-c0x00ffffff-no-rj',
    isLive: false,
    videoIds: [
      'SqfOtSrZUDI','rpKxxBf13pc','vNoO3YQAPNM',
      'Rfsp2ugbXiU','4oMd-rUCZnc','9mOOHHI5NfY'
    ],
  },

  {
    number: '04',
    name: '7 Hills Church',
    host: 'Pastor Marcus Mecum',
    type: 'CHURCH',
    category: 'favorites',
    vibe: 'alive',
    desc: 'Encounter Jesus. Experience life change. Expand heaven. Florence, KY.',
    website: 'https://7hillschurch.tv',
    youtubeChannelId: 'UC8qt6gDsT-3eXIOo7NBsrwA',
    thumbUrl: '',
    isLive: true,
    videoIds: [],
  },

  // ── LIVE CHURCH / SERMONS ─────────────────────────────────

  {
    number: '05',
    name: 'Elevation Church',
    host: 'Pastor Steven Furtick',
    type: 'CHURCH',
    category: 'church',
    vibe: 'cinematic',
    desc: 'Big production. Bigger faith. Charlotte, NC.',
    website: 'https://elevationchurch.org',
    youtubeChannelId: 'UCIQqvZbHSwX0yKNVK1MyYjQ',
    thumbUrl: '',
    isLive: true,
    videoIds: [],
  },

  {
    number: '06',
    name: 'Mosaic',
    host: 'Pastor Erwin McManus',
    type: 'CHURCH',
    category: 'church',
    vibe: 'creative',
    desc: 'Faith meets art meets culture. Los Angeles, CA.',
    website: 'https://mosaic.org',
    youtubeChannelId: 'UCz9PqE5Qr9avopAPkfCZcSQ',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '07',
    name: 'Lakepointe Church',
    host: 'Pastor Andy Addis',
    type: 'CHURCH',
    category: 'church',
    vibe: 'warm',
    desc: 'Know God. Find freedom. Discover calling. Make a difference. Rockwall, TX.',
    website: 'https://lakepointe.org',
    youtubeChannelId: 'UC5f7yO3WU_Ns0WDCQuP5bAw',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '08',
    name: 'Saddleback Church',
    host: 'Various Pastors',
    type: 'CHURCH',
    category: 'church',
    vibe: 'legacy',
    desc: 'Passionate about loving God and people. Lake Forest, CA.',
    website: 'https://saddleback.com',
    youtubeChannelId: 'UCkvTYtzvEDc7i0ATeWC-wHg',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '09',
    name: 'The Porch',
    host: 'Various Speakers',
    type: 'CHURCH',
    category: 'church',
    vibe: 'youth',
    desc: 'Young adults ministry of Watermark Church. Tuesday nights. Dallas, TX.',
    website: 'https://theporch.live',
    youtubeChannelId: 'UCvot08iHtei5WItdADfZl5g',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '10',
    name: 'Joseph Prince',
    host: 'Joseph Prince',
    type: 'CHURCH',
    category: 'church',
    vibe: 'grace',
    desc: 'Grace-focused gospel teaching. New Creation Church, Singapore.',
    website: 'https://josephprince.com',
    youtubeChannelId: 'UCJRSBsjLPipnu8y03qa2_Iw',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '11',
    name: 'Tony Evans',
    host: 'Dr. Tony Evans',
    type: 'CHURCH',
    category: 'church',
    vibe: 'deep',
    desc: 'Kingdom discipleship. Oak Cliff Bible Fellowship. Dallas, TX.',
    website: 'https://tonyevans.org',
    youtubeChannelId: 'UCRZweRCzcK5ObXPCNKvdMOQ',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '12',
    name: 'In Touch Ministries',
    host: 'Dr. Charles Stanley',
    type: 'CHURCH',
    category: 'church',
    vibe: 'classic',
    desc: 'A lifetime of biblical teaching. Trusted. Timeless.',
    website: 'https://intouch.org',
    youtubeChannelId: 'UCXL6kvDyoQpvtaeafC4pLyg',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '13',
    name: 'Billy Graham Evangelistic Association',
    host: 'Franklin Graham',
    type: 'CHURCH',
    category: 'church',
    vibe: 'legacy',
    desc: 'Historic crusades. Timeless gospel. Charlotte, NC.',
    website: 'https://billygraham.org',
    youtubeChannelId: 'UC29BKw2DaNMQe2B90QRVCNw',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '14',
    name: 'Churchome',
    host: 'Pastor Judah Smith',
    type: 'CHURCH',
    category: 'church',
    vibe: 'accessible',
    desc: 'Everyone regardless of background gets to hear the story of Jesus.',
    website: 'https://churchome.org',
    youtubeChannelId: 'UCxylcGrA3hG2G3v81qUD3vw',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '15',
    name: 'Creflo Dollar Ministries',
    host: 'Dr. Creflo Dollar',
    type: 'CHURCH',
    category: 'church',
    vibe: 'bold',
    desc: 'Understanding grace. Empowering change. World Changers Church International.',
    website: 'https://creflodollarministries.org',
    youtubeChannelId: 'UCBEcQzSjUXZcoeK7_Yy69sA',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  // ── REAL TALK / PODCASTS ──────────────────────────────────

  {
    number: '16',
    name: 'The George Janko Show',
    host: 'George Janko',
    type: 'PODCAST',
    category: 'real-talk',
    vibe: 'crossover',
    desc: 'Faith, life, and long conversations with people who matter.',
    website: 'https://thegeorgejankoshow.com',
    youtubeChannelId: 'UCLjBCYil92x3SYtHrvr3Pew',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '17',
    name: 'Girls Gone Bible',
    host: 'Angela Halili & Arielle Reitsma',
    type: 'PODCAST',
    category: 'real-talk',
    vibe: 'honest',
    desc: 'All things Jesus. All things life. Two imperfect girls. One perfect God.',
    website: 'https://girlsgonebible.com',
    youtubeChannelId: 'UCGbzCe9feKNpWXUJL_G5LjA',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '18',
    name: 'Ruslan KD',
    host: 'Ruslan Khadzhibaronov',
    type: 'PODCAST',
    category: 'real-talk',
    vibe: 'cultural',
    desc: 'Christian culture commentary. Faith, lifestyle, and real talk.',
    website: '',
    youtubeChannelId: 'UCj2yZE96gWsFyeVYnY9zXeg',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '19',
    name: 'Unashamed',
    host: 'Phil, Jase, Al & Zach Robertson',
    type: 'PODCAST',
    category: 'real-talk',
    vibe: 'southern',
    desc: 'Unashamed of the gospel. Stories of faith and family from West Monroe, LA.',
    website: '',
    youtubeChannelId: 'UCHnP4h7CkxDtQXV-kEGS9FA',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '20',
    name: 'WHOA That\'s Good',
    host: 'Sadie Robertson Huff',
    type: 'PODCAST',
    category: 'real-talk',
    vibe: 'lifestyle',
    desc: 'What is the best advice you have ever been given?',
    website: '',
    youtubeChannelId: 'UCl2vodgsQPqVhbZNGNyjUiQ',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '21',
    name: 'Bryce Crawford Podcast',
    host: 'Bryce Crawford',
    type: 'PODCAST',
    category: 'real-talk',
    vibe: 'honest',
    desc: 'Christ and the major topics facing Christianity and the world today.',
    website: '',
    youtubeChannelId: 'UCE63fBeQIoJ2P2mlBkQDchA',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '22',
    name: 'Unlearned Wisdom',
    host: 'Johnny Chang',
    type: 'PODCAST',
    category: 'real-talk',
    vibe: 'raw',
    desc: 'Gospel-centered lessons you can only learn through living them.',
    website: '',
    youtubeChannelId: 'UCPqYr2JcT_x5DmpTt96obWQ',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '23',
    name: 'Christ With Coffee On Ice',
    host: 'Ally Yost',
    type: 'PODCAST',
    category: 'real-talk',
    vibe: 'vulnerable',
    desc: 'Vulnerability, rawness, hope, and encouragement. Grab your iced coffee.',
    website: 'https://allyyost.com',
    youtubeChannelId: 'UCKsfCFlUNG0dR2Um7tpneNg',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  // ── THE OLD GUARD / PULPIT ────────────────────────────────

  {
    number: '24',
    name: 'Desiring God',
    host: 'John Piper',
    type: 'TEACHING',
    category: 'pulpit',
    vibe: 'deep',
    desc: 'Everlasting joy in Jesus Christ. 50+ years of biblical teaching.',
    website: 'https://desiringgod.org',
    youtubeChannelId: 'UCnrFlpro0xfYjz6s5Xa8WWw',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '25',
    name: 'Voddie Baucham Ministries',
    host: 'Dr. Voddie Baucham',
    type: 'TEACHING',
    category: 'pulpit',
    vibe: 'uncompromising',
    desc: 'Sound doctrine. Cultural apologetics. Gospel clarity.',
    website: '',
    youtubeChannelId: 'UC5G3vqNccg0DhsuqfYYSu7Q',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '26',
    name: 'HeartCry Missionary Society',
    host: 'Paul Washer',
    type: 'TEACHING',
    category: 'pulpit',
    vibe: 'raw',
    desc: 'That His name be great among the nations. No-compromise gospel preaching.',
    website: 'https://heartcrymissionary.com',
    youtubeChannelId: 'UCm6u_sCZttC70GyRh6uCurQ',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '27',
    name: 'Ligonier Ministries',
    host: 'R.C. Sproul & Teaching Fellows',
    type: 'TEACHING',
    category: 'pulpit',
    vibe: 'scholarly',
    desc: 'Founded by R.C. Sproul. Proclaiming the holiness of God to as many as possible.',
    website: 'https://ligonier.org',
    youtubeChannelId: 'UCut8939DdQsJI3Gw1ziAc4w',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  // ── APOLOGETICS / DEEP THINKING ───────────────────────────

  {
    number: '28',
    name: 'Wes Huff',
    host: 'Wesley Huff',
    type: 'APOLOGETICS',
    category: 'apologetics',
    vibe: 'scholarly',
    desc: 'PhD candidate. Biblical manuscripts, ancient texts, defending faith with calm precision.',
    website: 'https://wesleyhuff.com',
    youtubeChannelId: 'UCJX2EazMKUqBQV048px2aoA',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '29',
    name: 'Mike Winger',
    host: 'Mike Winger',
    type: 'APOLOGETICS',
    category: 'apologetics',
    vibe: 'deep',
    desc: 'Think biblically about everything. Deep Bible study. No shortcuts.',
    website: '',
    youtubeChannelId: 'UC7u2HaYBKDaLPcWmldxgGEA',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '30',
    name: 'InspiringPhilosophy',
    host: 'Michael Jones',
    type: 'APOLOGETICS',
    category: 'apologetics',
    vibe: 'intellectual',
    desc: 'Science meets faith. Philosophy meets theology. Livestreaming every Monday.',
    website: '',
    youtubeChannelId: 'UC5qDet6sa6rODi7t6wfpg8g',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '31',
    name: 'BibleProject',
    host: 'Tim Mackie & Jon Collins',
    type: 'EDUCATION',
    category: 'apologetics',
    vibe: 'visual',
    desc: 'Free animated resources to help you experience the whole Bible.',
    website: 'https://bibleproject.com',
    youtubeChannelId: 'UCVfwlh9XpX2Y_tQfjeln9QA',
    // Using playlist to avoid shorts — book overviews only
    playlistId: 'PLH0Szn1yYNedn4FbBMMtblW-GfHMbGMjJ',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '32',
    name: 'Cross Examined',
    host: 'Dr. Frank Turek',
    type: 'APOLOGETICS',
    category: 'apologetics',
    vibe: 'debate',
    desc: 'Cross-examining ideas against the truth of Christianity.',
    website: 'https://crossexamined.org',
    youtubeChannelId: 'UCedYGs_lqq1uNet0u7qlSyQ',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '33',
    name: 'Living Waters',
    host: 'Ray Comfort',
    type: 'APOLOGETICS',
    category: 'apologetics',
    vibe: 'street',
    desc: 'Street evangelism. Practical apologetics. Inspiring the Great Commission.',
    website: 'https://livingwaters.com',
    youtubeChannelId: 'UCmrVJGUS1u5-Hsm_BFS_1YA',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '34',
    name: 'Redeemed Zoomer',
    host: 'Anonymous Seminary Student',
    type: 'APOLOGETICS',
    category: 'apologetics',
    vibe: 'gen-z',
    desc: 'Reformed theology for the internet generation. Fighting theological drift.',
    website: '',
    youtubeChannelId: 'UCiLqiXa5O85APUBQV7X5w9Q',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '35',
    name: 'THE BEAT',
    host: 'Allen Parr',
    type: 'EDUCATION',
    category: 'apologetics',
    vibe: 'accessible',
    desc: 'Biblical Encouragement And Truth. Easy entry theology for every believer.',
    website: '',
    youtubeChannelId: 'UCm_RMW_fQk-ELpPYUzor8lw',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  // ── STREET / CAMPUS EVANGELISM ────────────────────────────

  {
    number: '36',
    name: 'Give Me An Answer',
    host: 'Cliffe & Stuart Knechtle',
    type: 'APOLOGETICS',
    category: 'street',
    vibe: 'campus',
    desc: '40 years on university campuses. Harvard. Stanford. UCLA. Real questions. Real answers.',
    website: 'https://givemeananswer.org',
    youtubeChannelId: 'UCKr-liguaGWMf3f94eQXsug',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  // ── PROPHECY / END TIMES ──────────────────────────────────

  {
    number: '37',
    name: 'Perry Stone Ministries',
    host: 'Perry Stone',
    type: 'TEACHING',
    category: 'prophecy',
    vibe: 'prophetic',
    desc: 'Manna-Fest. Prophecy, end times, Hebrew roots, spiritual warfare. Cleveland, TN.',
    website: 'https://perrystone.org',
    youtubeChannelId: 'UCHJ5B4pWmC7ULGYb1KI5Wjw',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  // ── CREATION SCIENCE ──────────────────────────────────────

  {
    number: '38',
    name: 'Dr. Dino',
    host: 'Kent Hovind',
    type: 'TEACHING',
    category: 'creation',
    vibe: 'controversial',
    desc: 'Creation science. Dinosaurs in the Bible. The most debated creationist alive.',
    website: 'https://drdino.com',
    youtubeChannelId: 'UCX-7N-nZ7Yh6nMO9mmdlMwA',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  // ── CHURCH HISTORY ────────────────────────────────────────

  {
    number: '39',
    name: 'Expedition Bible',
    host: 'Joel Kramer',
    type: 'HISTORY',
    category: 'history',
    vibe: 'archaeology',
    desc: 'Biblical archaeology. Walk the sites. Understand the context.',
    website: '',
    youtubeChannelId: 'UC5g_Zgi8TOC6GvvnxzQCY2w',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '40',
    name: 'Early Christian History',
    host: 'Dr. Michael F. Bird',
    type: 'HISTORY',
    category: 'history',
    vibe: 'scholarly',
    desc: 'NT scholar. Early church history. Ancient manuscripts. Biblical studies.',
    website: '',
    youtubeChannelId: 'UC21I7qYVHPsOzL9ujxiRWZA',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  // ── MUSIC STATIONS ────────────────────────────────────────
  // NOTE: Music channels use isLive + liveStreamVideoId for 24/7 streams
  // or playlistId for curated playlists instead of RSS channel feeds

  {
    number: '41',
    name: 'Christian Worship Mix',
    host: 'Various Artists',
    type: 'MUSIC',
    category: 'music',
    vibe: 'worship',
    desc: 'Top Christian songs. Worship, CCM, gospel. Auto-updating mix.',
    website: '',
    youtubeChannelId: '',
    playlistId: 'PL330A461779A9106A',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '42',
    name: 'Lo-fi Christian Prayer Room',
    host: 'The Lofi Christian',
    type: 'AMBIENT',
    category: 'music',
    vibe: 'peaceful',
    desc: 'Instrumental worship. Bible scenes. 24/7 live. For the ones who can\'t sleep.',
    website: '',
    youtubeChannelId: 'UCwckSFwCQbw_BiCzNab44Ng',
    liveStreamVideoId: 'qXPoj_VYb3U',
    thumbUrl: '',
    isLive: true,
    videoIds: [],
  },

  {
    number: '43',
    name: 'Integrity Music — Instrumental',
    host: 'Integrity Music',
    type: 'AMBIENT',
    category: 'music',
    vibe: 'instrumental',
    desc: '24/7 instrumental worship. No words. Just presence.',
    website: '',
    youtubeChannelId: '',
    liveStreamVideoId: 'VYXDfhgwTyM',
    thumbUrl: '',
    isLive: true,
    videoIds: [],
  },

  {
    number: '44',
    name: "Alex's Curated Mix",
    host: 'Your playlist',
    type: 'MUSIC',
    category: 'music',
    vibe: 'curated',
    desc: 'A personalized mix of channels and favorites from the Prodigal Robe experience.',
    website: '',
    youtubeChannelId: '',
    playlistId: '',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  // ── COMEDY ───────────────────────────────────────────────

  {
    number: '45',
    name: 'John Crist',
    host: 'John Crist',
    type: 'COMEDY',
    category: 'comedy',
    vibe: 'sharp',
    desc: 'Stand-up comedian. Net Positive Podcast. 1 billion views. Church culture has never been safer to laugh at.',
    website: 'https://johncristcomedy.com',
    youtubeChannelId: 'UCFq7vUgpjnVRZI-MzSvRZAA',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '46',
    name: 'Tim Hawkins',
    host: 'Tim Hawkins',
    type: 'COMEDY',
    category: 'comedy',
    vibe: 'family',
    desc: 'Musical comedian. 100M YouTube views. Full specials. Grocery truck driver turned legend.',
    website: 'https://timhawkins.net',
    youtubeChannelId: 'UCDYmrqySCqrHnah4LNUPt4w',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '47',
    name: 'The Skit Guys',
    host: 'Tommy Woodard & Eddie James',
    type: 'COMEDY',
    category: 'comedy',
    vibe: 'sketch',
    desc: 'God, heart and humor. Sketch comedy built for the church.',
    website: 'https://skitguys.com',
    youtubeChannelId: 'UCiZwlklzb4hPh4pSX98c3EA',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '48',
    name: 'Trey Kennedy',
    host: 'Trey Kennedy',
    type: 'COMEDY',
    category: 'comedy',
    vibe: 'millennial',
    desc: 'Sketches, social media crossover, Christian culture comedy.',
    website: '',
    youtubeChannelId: 'UCP7LUz8TKiOARTD8LdrVgXQ',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  // ── CATHOLIC / LITURGICAL ─────────────────────────────────

  {
    number: '49',
    name: 'Ascension Presents',
    host: 'Fr. Mike Schmitz & Team',
    type: 'CATHOLIC',
    category: 'catholic',
    vibe: 'approachable',
    desc: 'The truth and beauty of the Catholic faith through media. Everyone welcome.',
    website: 'https://ascensionpress.com',
    youtubeChannelId: 'UCVdGX3N-WIJ5nUvklBTNhAw',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '50',
    name: 'Bishop Mar Mari Emmanuel',
    host: 'Bishop Mar Mari Emmanuel',
    type: 'CATHOLIC',
    category: 'catholic',
    vibe: 'uncompromising',
    desc: 'Iraqi-born Assyrian bishop. Christ the Good Shepherd Church, Sydney, Australia. Came back to preach forgiveness the week after being stabbed at the altar.',
    website: '',
    youtubeChannelId: 'UCUon2JumMSa2nFVVmcCyNUQ',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  {
    number: '51',
    name: 'Pints With Aquinas',
    host: 'Matt Fradd',
    type: 'CATHOLIC',
    category: 'catholic',
    vibe: 'deep',
    desc: 'Long-form Catholic philosophical discussion. Pull up a pint.',
    website: '',
    youtubeChannelId: 'UClh4JeqYB1QN6f1h_bzmEng',
    thumbUrl: '',
    isLive: false,
    videoIds: [],
  },

  // ── AMBIENT / PRAYER ROOM ─────────────────────────────────

  {
    number: '52',
    name: 'Divine Rest',
    host: 'Scripture & Rain',
    type: 'AMBIENT',
    category: 'ambient',
    vibe: 'peaceful',
    desc: 'Peaceful Bible readings, meditations, and rain soundscapes. For the ones who can\'t sleep.',
    website: '',
    youtubeChannelId: 'UC5rEKo8VUooEj_jaI5-ApvA',
    liveStreamVideoId: 'qXPoj_VYb3U',
    thumbUrl: '',
    isLive: true,
    videoIds: [],
  },

];

// ── PROGRAMMING BLOCKS ────────────────────────────────────────
// Auto-tune maps time of day to category
const FQ_BLOCKS = [
  { start: 6,  end: 9,  name: 'MORNING WORSHIP',  cat: 'music'       },
  { start: 9,  end: 12, name: 'DEEP THEOLOGY',     cat: 'pulpit'      },
  { start: 12, end: 15, name: 'SERMONS',            cat: 'church'      },
  { start: 15, end: 18, name: 'REAL TALK',          cat: 'real-talk'   },
  { start: 18, end: 20, name: 'LIVE CHURCH',        cat: 'favorites'   },
  { start: 20, end: 22, name: 'PRIME TIME',         cat: 'apologetics' },
  { start: 22, end: 24, name: 'LATE NIGHT',         cat: 'real-talk'   },
  { start: 0,  end: 3,  name: 'AFTER HOURS',       cat: 'comedy'      },
  { start: 3,  end: 6,  name: 'PRAYER ROOM',       cat: 'ambient'     },
];

// ── MIN DURATION FILTER ───────────────────────────────────────
// Videos shorter than this get skipped (blocks shorts)
const FQ_MIN_DURATION_SECONDS = 120; // 2 minutes minimum
